export const discs = [
    {
        id: '1',
        name: 'Innova Destroyer',
        weight: '170-175g',
        speed: '12',
        glide: '5',
        turn: '-1',
        fade: '3',
        type: 'distance driver',
        graphic: 'yellow knight',
    },
    {
        id: '2',
        name: 'Discraft Buzzz',
        weight: '178g',
        speed: '5',
        glide: '4',
        turn: '-1',
        fade: '1',
        type: 'mid-range',
        graphic: 'white bee',
    },
    {
        id: '3',
        name: 'Discraft Luna',
        weight: '170-174g',
        speed: '3',
        glide: '3',
        turn: '0',
        fade: '3',
        type: 'putt and approach',
        graphic: 'blue',
    },
    {
        id: '4',
        name: 'Innova Wraith',
        weight: '170-175g',
        speed: '11',
        glide: '5',
        turn: '-1',
        fade: '3',
        type: 'distance driver',
        graphic: 'yellow wraith',
    },
    {
        id: '5',
        name: 'Discraft Zone',
        weight: '170g',
        speed: '4',
        glide: '3',
        turn: '0',
        fade: '3',
        type: 'putt and approach',
        graphic: 'jawbreaker',
    },
]