export const discs = [
    {
        id: 'destroyer',
        name: 'Innova Destroyer',
        stats: '12, 5, -1, 3',
        type: 'Distance Driver',
        graphic: 'yellow knight',
        category: 'sports',
        price: '$24.99',
        img: './assets/destroyer2.jpeg',
    },
    {
        id: 'buzzz',
        name: 'Discraft Buzzz',
        stats: '5, 4, -1, 1',
        type: 'Mid-Range',
        graphic: 'white bee',
        category: 'sports',
        price: '$14.95',
        img: './assets/disc-buzzz.webp',
    },
    {
        id: 'luna',
        name: 'Discraft Luna',
        stats: '3, 3, 0, 3',
        type: 'Putt & Approach',
        graphic: 'blue',
        category: 'sports',
        price: '$24.99',
        img: './assets/disc-luna.webp',
    },
    {
        id: 'wraith',
        name: 'Innova Wraith',
        stats: '11, 5, -1, 3',
        type: 'Distance Driver',
        graphic: 'yellow wraith',
        category: 'sports',
        price: '$24.99',
        img: './assets/yellow-wraith.jpeg',
    },
    {
        id: 'jawbreaker',
        name: 'Discraft Zone',
        stats: '4, 3, 0, 3',
        type: 'Putt & Approach',
        graphic: 'jawbreaker',
        category: 'sports',
        price: '$17.99',
        img: './assets/jawbreaker.jpeg',
    },
    {
        id: 'firebird',
        name: 'Innova Firebird',
        stats: '9, 3, 0, 4',
        type: 'Distance Driver',
        graphic: 'lime green',
        category: 'sports',
        price: '$21.99',
        img: './assets/firebird-disc.jpeg',
    }
]