export const discs = [
    {
        id: 'destroyer',
        name: 'Innova Destroyer',
        speed: '12',
        glide: '5',
        turn: '-1',
        fade: '3',
        type: 'distance driver',
        graphic: 'yellow knight',
        category: 'sports',
        price: '$24.99',
        img: './assets/destroyer2.jpeg',
    },
    {
        id: 'buzzz',
        name: 'Discraft Buzzz',
        speed: '5',
        glide: '4',
        turn: '-1',
        fade: '1',
        type: 'mid-range',
        graphic: 'white bee',
        category: 'sports',
        price: '$14.95',
        img: './assets/disc-buzzz.webp',
    },
    {
        id: 'luna',
        name: 'Discraft Luna',
        speed: '3',
        glide: '3',
        turn: '0',
        fade: '3',
        type: 'putt and approach',
        graphic: 'blue',
        category: 'sports',
        price: '$24.99',
        img: './assets/disc-luna.webp',
    },
    {
        id: 'wraith',
        name: 'Innova Wraith',
        speed: '11',
        glide: '5',
        turn: '-1',
        fade: '3',
        type: 'distance driver',
        graphic: 'yellow wraith',
        category: 'sports',
        price: '$24.99',
        img: './assets/yellow-wraith.jpeg',
    },
    {
        id: 'jawbreaker',
        name: 'Discraft Zone',
        speed: '4',
        glide: '3',
        turn: '0',
        fade: '3',
        type: 'putt and approach',
        graphic: 'jawbreaker',
        category: 'sports',
        price: '$17.99',
        img: './assets/jawbreaker.jpeg',
    },
    {
        id: 'firebird',
        name: 'Innova Firebird',
        speed: '9',
        glide: '3',
        turn: '0',
        fade: '4',
        type: 'distance driver',
        graphic: 'lime green',
        category: 'sports',
        price: '$21.99',
        img: './assets/firebird',
    }
]